### PR TITLE
Catch exceptions when loading types

### LINKED ISSUE #21: Endpoint crashes if a type can not be found
It could happen in a few scenarios:

- When there is a typo in the routing file (resulting type not to be found)
- When the assembly can not be found or loaded

### PR DESCRIPTION
**Pull request by HEskandari**
Resolves #21

### CODE REVIEW

File: src/NServiceBus.FileBasedRouting/XmlRoutingFileParser.cs [hunk 1]
```diff
@@ -42,23 +45,32 @@ public IEnumerable<EndpointRoutingConfiguration> Parse(XDocument document)
...
 
-        static IEnumerable<Type> GetAllMessageTypes(XElement endpointElement, string singular, string plural)
+        IEnumerable<Type> GetAllMessageTypes(XElement endpointElement, string singular, string plural)
         {
             var handles = endpointElement.Element("handles");
 
             var separatelyConfiguredCommands = handles
                 ?.Elements(singular)
                 .Select(e => SelectCommand(e.Attribute("type").Value))
+                .Where(e => e != null)
```
Comment (timbussmann) [inline src/NServiceBus.FileBasedRouting/XmlRoutingFileParser.cs]: wouldn't this cause invalid parts of the configuration to be "silently" ignored?

Comment (SzymonPobiega) [reply src/NServiceBus.FileBasedRouting/XmlRoutingFileParser.cs]: It logs a `warn` so I think it should be enough.

**Review by SzymonPobiega — APPROVED** [review]

File: src/NServiceBus.FileBasedRouting/XmlRoutingFileParser.cs (hunk 1 above)
Comment (HEskandari) [reply src/NServiceBus.FileBasedRouting/XmlRoutingFileParser.cs]: it does and that's the point. In a centralized configuration, you have all the routes, even though those messages / types might not be available on that endpoint.

I also thought a `warn` log would be enough.

Comment (SzymonPobiega) [reply src/NServiceBus.FileBasedRouting/XmlRoutingFileParser.cs]: I think ideally (not sure if this is possible in a reliable way) for a given type `t` we should check if we know it's assembly. If not, we ignore such a type without logging warning. We would only warn if we know the assembly name is fine and we have it loaded but the type name is not recognized. 

We risk that a route with an invalid assembly name will be silently ignored but I think it might be better than logging `warn` for each unknown type if the message contracts are spread across many assemblies.

Comment (timbussmann) [reply src/NServiceBus.FileBasedRouting/XmlRoutingFileParser.cs]: I'm on board with avoiding exceptions because the specific assembly isn't available on a given endpoint. But according to the linked issue, this would also silently ignore spelling errors although a given type might be available. The later scenario doesn't seem to be something we would want to swallow in my opinion, but at that point, I'm not sure how we could limit ourselves to the first scenario?

Comment (SzymonPobiega) [reply src/NServiceBus.FileBasedRouting/XmlRoutingFileParser.cs]: How about an option "I send messages from this assembly" declaration? By default we load all the types in each endpoints and log `warn` in the current code.

But if a given endpoint includes the list of assemblies it "knows", we ignore all routes for types from different assemblies. Yes, it adds a bit of effort in the multiple contract assembly case but it saves you `warn`s that are false positives.

e.g.
```
<endpoints>
  <endpoint name="endpointA">
    <contracts>
       <contract assembly="MyContracts"/>
    </contracts>
    <handles>
      <command type="Contracts.Commands.DemoCommand, Contracts" />
      <event type="Contracts.Events.DemoEvent, Contracts" />
    </handles>
  </endpoint>
  <endpoint name="endpointb">
```

Comment (HEskandari) [reply src/NServiceBus.FileBasedRouting/XmlRoutingFileParser.cs]: @timbussmann I'm still wondering why a `warn` would not work in the case of an spelling issue? How would you validate the endpoint name? Is there way to ensure there's no spelling mistake there? Why is the assembly/type different?

Comment (timbussmann) [reply src/NServiceBus.FileBasedRouting/XmlRoutingFileParser.cs]: @SzymonPobiega hm that would work but I think an additional declaration adds quite a bit of pain to configure routing :( In that case I think I'd prefer going with @HEskandari suggested approach and log warnings.

@HEskandari I'm not aware of any validation regarding endpoint name. That's a good point. Although I think there's a bigger chance that you mispell some of the types and at least there we could help you by identifying that this type isn't around, it's a perfectly valid point that the assembly of a completely unrelated endpoint might not be around. Also, in case of commands, it should be less of an issue as send will also throw in case no route was found. So let's go ahead with your proposed changes 👍

File: src/NServiceBus.FileBasedRouting/XmlRoutingFileParser.cs [hunk 2]
```diff
@@ -42,23 +45,32 @@ public IEnumerable<EndpointRoutingConfiguration> Parse(XDocument document)
...
+        Type SelectCommand(string typeName)
         {
-            return Type.GetType(typeName, true);
+            try
+            {
+                return Type.GetType(typeName, true);
+            }
+            catch
+            {
+                logger.Warn($"Could not find type {typeName}.");
```
Comment (timbussmann) [inline src/NServiceBus.FileBasedRouting/XmlRoutingFileParser.cs]: should we improve that log statement? In many cases, the GetType call shouldn't throw but just return null. In that case we don't log while if theres some exception, it's probably not about the type not being found, but something else. Maybe something like:
```
var type;
try
{
    type = Type.GetType(...)
} 
catch
{
    // ignore 
}

if(type == null)
{
    logger.Warn("cannot add route for unknown type ...");
}

return type;
```

**Comment by HEskandari** [comment]
@timbussmann @SzymonPobiega Updated. Also changed the method name as it was used for both events and commands.

File: src/NServiceBus.FileBasedRouting/XmlRoutingFileParser.cs [hunk 3]
```diff
@@ -5,13 +5,16 @@
...
 using System.Xml.Schema;
+using NServiceBus.Logging;
 
 namespace NServiceBus.FileBasedRouting
 {
     class XmlRoutingFileParser
     {
         public XmlRoutingFileParser()
         {
+            logger = LogManager.GetLogger(typeof(XmlRoutingFileParser));
```
Comment (timbussmann) [inline src/NServiceBus.FileBasedRouting/XmlRoutingFileParser.cs]: loggers are usually static in core. I'd say let's align with core.

File: src/NServiceBus.FileBasedRouting/XmlRoutingFileParser.cs [hunk 4]
```diff
@@ -42,23 +45,40 @@ public IEnumerable<EndpointRoutingConfiguration> Parse(XDocument document)
...
+                .Where(e => e != null)
                 .ToArray() ?? Type.EmptyTypes;
 
             var filteredCommands = handles?.Elements(plural).SelectMany(SelectMessages) ?? Type.EmptyTypes;
             var allCommands = separatelyConfiguredCommands.Concat(filteredCommands).Distinct();
             return allCommands;
         }
 
-        static Type SelectCommand(string typeName)
+        Type FindMessageType(string typeName)
```
Comment (timbussmann) [inline src/NServiceBus.FileBasedRouting/XmlRoutingFileParser.cs]: can be static again once logger is static

File: src/NServiceBus.FileBasedRouting/XmlRoutingFileParser.cs [hunk 5]
```diff
@@ -42,23 +45,40 @@ public IEnumerable<EndpointRoutingConfiguration> Parse(XDocument document)
             return configs;
         }
 
-        static IEnumerable<Type> GetAllMessageTypes(XElement endpointElement, string singular, string plural)
+        IEnumerable<Type> GetAllMessageTypes(XElement endpointElement, string singular, string plural)
```
Comment (timbussmann) [inline src/NServiceBus.FileBasedRouting/XmlRoutingFileParser.cs]: can be static again once logger is static

**Review by timbussmann — CHANGES_REQUESTED** [review]

**Comment by HEskandari** [comment]
@timbussmann updated.

**Review by timbussmann — APPROVED** [review]
